version: '3.8'

services:
  client:
    container_name: grpc-client
    image: grpc-client
    build: 
      context: ./client
    ports:
      - 3000:3000
  server:
    container_name: grpc-server
    image: grpc-server
    build: 
      context: ./server
    ports:
      - 9090:9090
  proxy:
    container_name: grpc-proxy
    image: grpc-proxy
    build: 
      context: ./proxy
    ports:
      - 8080:8080
      - 9901:9901
